using System;
using NUnit.Framework;
using GhSA;
using GhSA.Parameters;
using Rhino.Geometry;
using Rhino;
using Grasshopper;
using GsaAPI;

namespace ComponentsTest
{
    public class ModelTests
    {
        [TestCase]
        public void OpenComponentTest()
        {
            // create the component
            var comp = new GhSA.Components.OpenModel();
            comp.CreateAttributes();

            // input parameter
            // set filename to be openend
            string file = GhSA.Util.Gsa.GsaPath.GetPath + "\\Samples\\Steel\\Steel_Design_Simple.gwb";
            // instantiate new panel
            var panel = new Grasshopper.Kernel.Special.GH_Panel();
            panel.CreateAttributes();
            // set panel data as usertext
            panel.UserText = file;
            // add panel to component input
            comp.Params.Input[0].AddSource(panel);

            // run component calculation
            comp.ExpireSolution(true);

            // read output data
            comp.Params.Output[0].CollectData();
            // set output data to Gsa-goo type
            GsaModelGoo output = (GsaModelGoo)comp.Params.Output[0].VolatileData.get_Branch(0)[0];

            // cast from -goo to Gsa-GH data type
            GsaModel model = new GsaModel();
            output.CastTo(ref model);

            Assert.AreEqual(file, model.FileName);
        }
    }
}